### ISSUE TITLE
Autodetect the number of threads in the CPU usage panel

### ISSUE THREAD

**Issue by vdemonchy** [ragesaq/gamergraf#2]
Hello,

First of all, I'd like to thank you a lot for your work, it works flawlessly on my computer after following your detailed installation guide. You sir definitely deserve more stars :).

Now, I'd like to suggest a small improvement for the CPU usage panel. By default, it has fixed number of 4 CPU threads, meaning that you have to edit the panel if you don't have that exact number on your machine as you say in your readme (which is my case).

To fix that, you could simply replace the 4 similar queries by a single one :
`aliasSub(collectd.$Computer.curl_xml-afterburner.gauge-CPU[0-9]*_usage, '.*CPU(\d+)_usage', 'CPU #\1 usage')`

With this single query, it now displays correctly with any number of threads as shown here :
<img width="660" alt="cpu" src="https://cloud.githubusercontent.com/assets/3669072/25921117/8dcdcb72-35d4-11e7-86e8-469ce4719100.PNG">

**Comment by ragesaq** [comment]
Nice query-fu! I'll get this in soon.

**Comment by vdemonchy** [comment]
That's cool, I'll probably have a few other enhancements coming in the near future :)

**Comment by ragesaq** [comment]
Updated. Keep em coming!
